services:
  torizon-os-build-status-data-acquisition:
    networks:
    - influxdbnet
    - frontend
    image: leograba/torizon-os-build-status-data-acquisition:0.1.1
    depends_on:
    - influxdb
    command:
    - influxdb
    - "8086"
    environment:
    - DEBUG=1
  influxdb:
    networks:
    - influxdbnet
    image: influxdb:2.7.1-alpine
    environment:
    - DOCKER_INFLUXDB_INIT_MODE=setup
    - DOCKER_INFLUXDB_INIT_USERNAME=torizon
    - DOCKER_INFLUXDB_INIT_PASSWORD=T0rizonEasy2Us&
    - DOCKER_INFLUXDB_INIT_ORG=toradex
    - DOCKER_INFLUXDB_INIT_BUCKET=jenkinsdatabucket
    - DOCKER_INFLUXDB_INIT_RETENTION=60m
    - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=T0rizonTh3Ea&IndustrialPlatform
  grafana:
    volumes:
    - $PWD/debug/grafana-config/grafana.ini:/etc/grafana/grafana.ini
    - $PWD/debug/grafana-config/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    - $PWD/debug/grafana-config/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
    - $PWD/debug/grafana-config/dashboard.json:/var/lib/grafana/dashboards/dashboard.json
    image: grafana/grafana:10.1.6
    ports:
    - 3000:3000
    networks:
    - influxdbnet
    - frontend
    depends_on:
    - influxdb
    - torizon-os-build-status-data-acquisition
networks:
  influxdbnet:
    internal: true
  frontend:
    internal: false
version: "3.9"
