version: "3.9"
services:
  torizon-os-build-status-data-acquisition:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_LOGIN}/torizon-os-build-status-data-acquisition:${TAG}
