name: OpenSCAD Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y --no-install-recommends openscad
        mkdir -p $HOME/.local/share/OpenSCAD/libraries
        cd $HOME/.local/share/OpenSCAD/libraries
        git clone https://github.com/BelfrySCAD/BOSL2.git
        git clone https://github.com/nophead/NopSCADlib.git

    - name: Build STL files
      run: |
        # Replace '*.scad' with the actual pattern for your OpenSCAD files
        for file in $(find . -name '*.scad'); do
          openscad -o "${file%.scad}.stl" "$file"
        done

    - name: Upload STL files
      uses: actions/upload-artifact@v2
      with:
        name: stl-files
        path: ./*.stl
