name: Grafana

env:
  wdir: TorizonOSBuildStatusGrafana

on:
  push:
    paths:
      - 'TorizonOSBuildStatusGrafana/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.wdir }}

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get container tag
        run: |
          echo "CONTAINER_TAG=$(jq -r '.docker_tag' .vscode/settings.json)" >> $GITHUB_ENV

      - name: Build and push release candidate
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ${{ env.wdir }}
          build-args: |
            IMAGE_ARCH=arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/torizon-os-build-status-grafana:rc
